name:               "Plant profile"
description:        "Plant profile"

url:                ""
author:             "plantprofile"
email:              "plantprofile@plantprofile.net"
gravatar_hash:      "14cded646890924972c7e67585ea51a9"
twitter:            ""
email:              "plantprofile@plantprofile.net"
github:             ""
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   ""

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate